//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by OpenGL.rc
//
#define IDD_ABOUTBOX                    100
#define IDS_DEFAULT_FONT                111
#define IDR_MAINFRAME                   128
#define IDR_OPENGLTYPE                  129
#define IDD_QUIT_DIALOG                 136
#define IDD_CREATE_SPATH                155
#define IDD_SET_RADIUS                  160
#define IDD_TILE_FACES                  164
#define IDD_TILE                        165
#define IDD_MATERIAL_DIALOG             167
#define IDD_MESHINFO                    168
#define IDC_CSP_SRC                     1040
#define IDC_CSP_DIST                    1041
#define ID_STATIC                       1046
#define ID_STATIC2                      1047
#define IDC_RADIUS_SPH                  1048
#define IDC_RADIUS_CYL                  1049
#define IDCLEAR                         1049
#define IDC_CSP_LENGTH                  1050
#define IDC_TXT_SGV                     1051
#define IDC_TXT_SGE                     1052
#define IDC_TXT_GAMMA                   1053
#define IDC_ESP_LENGTH                  1054
#define IDC_RADIO_SP_APPROX             1055
#define IDC_RADIO_SP_EXACT              1056
#define IDC_RADIO_SP_BOTH               1057
#define IDC_TXT_AVRSP                   1058
#define IDC_ASP_TIME                    1059
#define IDC_ESP_TIME                    1060
#define IDC_OBJ_VTX                     1061
#define IDC_OBJ_EDGE                    1062
#define IDC_OBJ_FACE                    1063
#define IDC_SP_GAMMA_SET                1068
#define IDC_TILEEDGE_BUTTON_OK          1081
#define IDC_TILEEDGE_BUTTON_CANCEL      1084
#define IDC_TILEEDGE_BUTTON_CLEAR       1085
#define IDC_TILEFACE_LIST               1089
#define IDC_MAKEEDGE_RB                 1090
#define IDC_REMESH_BUTTON_OK            1091
#define IDC_REMESH_BUTTON_CANCEL        1092
#define IDC_MATL_PPD_CHECK              1093
#define IDC_REMESH_BUTTON_CLEAR         1093
#define IDC_MAKEFACE_RB                 1094
#define IDC_MATERIAL_LIST               1095
#define IDC_REMESHING_RB                1095
#define IDC_DELEDGE_RB                  1096
#define IDC_SELECT_TILE_TXT             1097
#define IDC_REMESH_PATTERN_COMBO        1098
#define IDC_SELECT_CENTER_VERTEX_BUTTON 1099
#define IDC_DELFACE_RB                  1100
#define IDC_SELECT_CENTER_VERTEX_TXT    1101
#define IDC_MESH_INFO_EDIT              1101
#define IDC_EDIT_REMESH_NDIV            1103
#define IDC_TILE_TXT_SGV                1104
#define IDC_TILE_TXT_SGE                1105
#define IDC_TILE_TXT_GAMMA              1106
#define IDC_TILE_SP_GAMMA_SET           1107
#define IDC_TILE_TXT_AVRSP              1108
#define IDC_PARAMORG_RB                 1109
#define IDC_PARAMTP_RB                  1110
#define IDC_PARAMEW_RB                  1111
#define IDC_PARAMFW_RB                  1112
#define IDC_RECALC_PARAM_CB             1113
#define IDC_PARAMCONV_RB                1114
#define IDC_MAKECFACE_RB                1115
#define IDC_RADIO_PC_GEODIS             1119
#define IDC_RADIO_PC_CHORD              1121
#define IDC_RADIO_PC_NO                 1122
#define ID_MENU_SCREEN_WIREFRAME        32777
#define ID_MENU_SCREEN_SHADING          32778
#define ID_MENU_SCREEN_LOOP             32781
#define ID_MENU_SCREEN_SPATH            32783
#define ID_MENU_SCREEN_COAXIS           32785
#define ID_MENU_SCREEN_VERT             32786
#define ID_FILE_OPEN_DIST               32787
#define ID_FILE_OPEN_GMH                32789
#define ID_FILE_SAVE_GMH                32793
#define ID_FILE_SAVE_SRC                32794
#define ID_FILE_SAVE_DIST               32795
#define ID_MENU_SPATH_CREATE            32796
#define ID_MENU_SCREEN_ENHANCED         32805
#define ID_MENU_SCREEN_SMOOTH           32806
#define ID_MENU_SCREEN_INTERP           32808
#define ID_MENU_GENER_INTERP            32816
#define ID_FILE_OPEN_GPPD               32817
#define ID_FILE_SAVE_GPPD               32818
#define ID_MENU_SCREEN_RADIUS           32819
#define ID_MENU_SET_CONST               32820
#define ID_VIEW_BACKGROUND              32821
#define ID_MENU_SPATH_ANIM              32822
#define ID_MENU_SCREEN_VERTID           32823
#define ID_MENU_SCREEN_EDGEID           32824
#define ID_FILE_OPEN_SP                 32825
#define ID_MENU_SCREEN_SUBGRAPH         32826
#define ID_MENU_EDIT_LINES              32827
#define ID_FILE_OPEN_VW                 32829
#define ID_FILE_SAVE_VW                 32830
#define ID_MENU_EDIT_TILE               32831
#define ID_VIEW_MATERIAL                32832
#define ID_MENU_FAIRING_SP              32833
#define ID_MESH_INFO                    32834
#define ID_VIEW_GRADIENT                32835
#define ID_MENU_SCREEN_LIGHT0           32836
#define ID_MENU_SCREEN_LIGHT1           32837
#define ID_MENU_SCREEN_LIGHT2           32838
#define ID_MENU_SCREEN_LIGHT3           32839
#define ID_FILE_OPEN_SMF                32840
#define ID_FILE_SAVE_SMF                32841
#define ID_FILE_OPEN_MDW                32842
#define ID_FILE_SAVE_MDW                32843
#define ID_FILE_SAVEAS_MDW              32844
#define ID_MENU_SCREEN_REMESH           32845
#define ID_MENU_SCREEN_REMESHBOUN       32846
#define ID_MENU_SCREEN_GRPMESH          32847
#define ID_MENU_SCREEN_HIDDEN           32848
#define ID_EDIT_CREATE_SPATH            33009
#define IDS_CREATE_SPATH                61213
#define IDS_PATTERN_LATTICE             61214
#define IDS_PATTERN_RADIAL              61215
#define IDS_SELECTED_PROMPT             61216

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        172
#define _APS_NEXT_COMMAND_VALUE         32849
#define _APS_NEXT_CONTROL_VALUE         1120
#define _APS_NEXT_SYMED_VALUE           114
#endif
#endif
